const AOI = [{
		"OBJECTID": 1,
		"ort": "Kranebitten (Grünes Band)",
		"adresse": "Kranebitten Allee",
		"typ": ["Fussball", "Klettern", "Skaten","Fitness","Tischtennis","Basketball","Slackline","Hundepark"],
		"gruppe": "Sport",
		"lng": 11.326352,
		"lat": 47.264974,
		"icon": "fußball",
		"bild": "images/aoi/test.jpg"
	},
	{
		"OBJECTID": 2,
		"ort": "Innauen bei Kranebitten",
		"adresse": "Kranebitter Allee",
		"typ": ["Naherholung"],
		"gruppe": "Naherholung",
		"lng": 11.328901,
		"lat": 47.259157,
		"icon": "sonnenschirm"
	},
	{
		"OBJECTID": 3,
		"ort": "Innauen Völs",
		"adresse": "Inntalradweg",
		"typ": ["Naherholung"],
		"gruppe": "Naherholung",
		"lng": 11.330395,
		"lat": 47.25639,
	},
	{
		"OBJECTID": 4,
		"ort": "Stromhaus Pulverturm",
		"adresse": "Hans-Flöckinger-Promenade",
		"typ": ["Naherholung"],
		"gruppe": "Naherholung",
		"lng": 11.354094,
		"lat": 47.255374,
		"icon": "sonnenschirm"
	},
	{
		"OBJECTID": 5,
		"ort": "Pulverturm",
		"adresse": "Inntalradweg - Pulverturm",
		"typ": ["Skate","Basketball","Slackline","Beachvolleyball","Fussball"],
		"gruppe": "Sport",
		"lng": 11.355904,
		"lat": 47.255843,
		"icon": "skate"
	},
	{
		"OBJECTID": 6,
		"ort": "Spielplatz – Dr.Stumpfstraße",
		"adresse": "Dr.Stumpfstraße",
		"typ": ["Spielplatz"],
		"gruppe": "Spielplatz",
		"lng": 11.365035,
		"lat": 47.254069,
		"icon": "spielplatz"
	},
	{
		"OBJECTID": 7,
		"ort": "Arthur-Haidl-Promenade",
		"adresse": " Arthur-Haidl-Promenade ",
		"typ": ["Hundespielplatz"],
		"gruppe": "Tier",
		"lng": 11.376568,
		"lat": 47.257611,
	},
	{
		"OBJECTID": 8,
		"ort": "Prandtauer Ufer",
		"adresse": "Prandtauerufer",
		"typ": ["Tischtennis","Basketball","Spielplatz"],
		"gruppe": "Sport",
		"lng": 11.380457,
		"lat": 47.262284,
		"icon": "tischtennis"
	},
	{
		"OBJECTID": 9,
		"ort": "Prandtauer Fitness",
		"adresse": "Prandtauerufer",
		"typ": ["Fitness"],
		"gruppe": "Sport",
		"lng": 11.381841,
		"lat": 47.263713,
		"icon": "fitness"
	},
	{
		"OBJECTID": 10,
		"ort": "Slacklinepark Universität",
		"adresse": "Prandtauerufer 8",
		"typ": ["Slackline"],
		"gruppe": "Sport",
		"lng": 11.382539,
		"lat": 47.264433,
		"icon": "slackline"
	},
	{
		"OBJECTID": 11,
		"ort": "Innpromenade",
		"adresse": "Franz-Gschnitzer-Promenade",
		"typ": ["Tischtennis","Spielplatz"],
		"gruppe": "Spielplatz",
		"lng": 11.381702,
		"lat": 47.261571,
		"icon": "tischtennis"
	},
	{
		"OBJECTID": 12,
		"ort": "Innufer Universität Campus Innrain",
		"adresse": "Universität Campus Innrain",
		"typ": ["Naherholung"],
		"gruppe": "Naherholung",
		"lng": 11.383874,
		"lat": 47.264145,
		"icon": "sonnenschirm"
	},
	{
		"OBJECTID": 13,
		"ort": "Lukis Yogawiese",
		"adresse": "Maria Hilf Park",
		"typ": ["Naherholung"],
		"gruppe": "Naherholung",
		"lng": 11.385539,
		"lat": 47.266607,
		"icon": "yoga"
	},
	{
		"OBJECTID": 14,
		"ort": "Waltherpark",
		"adresse": "Vogelweide",
		"typ": ["Naherholung","Spielplatz","Basketball","Fussball"],
		"gruppe": "Naherholung",
		"lng": 11.391566,
		"lat": 47.270084,
		"icon": "sonnenschirm"
	},
	{
		"OBJECTID": 15,
		"ort": "Kongress Park",
		"adresse": "Rennweg",
		"typ": ["Naherholung"],
		"gruppe": "Naherholung",
		"lng": 11.39497,
		"lat": 47.272223,
		"icon": "slackline"
	},
	{
		"OBJECTID": 16,
		"ort": "Emile Béthouarte-Steg",
		"adresse": "Innstraße",
		"typ": ["Naherholung"],
		"gruppe": "Naherholung",
		"lng": 11.39497,
		"lat": 47.273795,
		"icon": "sonnenschirm"
	},
	{
		"OBJECTID": 17,
		"ort": "Löwenhaus",
		"adresse": "Rennweg",
		"typ": ["Naherholung"],
		"gruppe": "Naherholung",
		"lng": 11.398381,
		"lat": 47.27676,
		"icon": "sonnenschirm"
	},
	{
		"OBJECTID": 18,
		"ort": "Huttererpark",
		"adresse": "Anni-Kraus-Weg",
		"typ": ["Spielplatz","Fitness"],
		"gruppe": "Spielplatz",
		"lng": 11.401041,
		"lat": 47.278321,
		"icon": "spielplatz"
	},
	{
		"OBJECTID": 19,
		"ort": "Saggen Grün",
		"adresse": "Saggen",
		"typ": ["Naherholung"],
		"gruppe": "Naherholung",
		"lng": 11.410826,
		"lat": 47.279507,
		"icon": "sonnenschirm"
	},
	{
		"OBJECTID": 20,
		"ort": "Sillmündung",
		"adresse": "Tiflisbrücke",
		"typ": ["Naherholung"],
		"gruppe": "Naherholung",
		"lng": 11.417007,
		"lat": 47.278119,
		"icon": "sonnenschirm"
	},
	{
		"OBJECTID": 21,
		"ort": "Reichenaupark",
		"adresse": "Reichenauer Straße",
		"typ": ["Skate","Volleyball","Basketball","Tischtennis","Klettern","Fussball"],
		"gruppe": "Sport",
		"lng": 11.427619,
		"lat": 47.274766,
		"icon": "skate"
	},
	{
		"OBJECTID": 22,
		"ort": "O-Dorf",
		"adresse": "An-der-Lan-Straße",
		"typ": ["Beachvolleyball","Slackline","Fitness","Fussball"],
		"gruppe": "Sport",
		"lng": 11.437988,
		"lat": 47.272102,
		"icon": "beachvolleyball"
	},
];